apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: dvh-etl-tools
  name: image-dvh-airflow-kafka
  namespace: dvh-etl-tools
spec:
  # no schedule, runs once
  image: "{{ image }}"
  backoffLimit: 0
  # Startup and exit. This job is never used, except for building the image and tracing vulnerabilities
  command:
    - "python3"
    - "-c"
    - "print('Completed')"