# github actions
name: Publish to ghcr

on:
  push:
    branches:
      - main
      - feat**
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"
  TEAM: dvh-etl-tools
  GAR_TEAM_SERVICE_ACCOUNT: "gar-dvh-etl-tools-9f1b@nais-management-233d.iam.gserviceaccount.com"
  NAIS_WORKLOAD_IDENTITY_PROVIDER: "projects/898056957967/locations/global/workloadIdentityPools/nav-identity-pool/providers/github-oidc-provider"


jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Add sha to environment variable"
        env:
          FULL_SHA: "${{github.sha}}"
          REF: "${{github.ref}}"
        run: |
          TAG=$(git log -1 --pretty=%ad --date=format:%Y%m%d-%H%M%S)
          branch="$(echo "$REF" | cut -c12-)"
          if [ "$branch" = "main" ]
          then
              echo "IMAGE=$IMAGE_NAME:$TAG" >> $GITHUB_ENV
          else 
              safe_branch=$(echo "$branch" | sed 's/[^a-zA-Z0-9._-]/-/g')
              echo "IMAGE=$IMAGE_NAME-$safe_branch:$TAG" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      # to fetch the chain guard image from GAR
      - id: gcloud_auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093  # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GAR_TEAM_SERVICE_ACCOUNT }}

      # to fetch the chain guard image from GAR
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        name: Login to Google Artifact Registry
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcloud_auth.outputs.access_token }}

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
